stage: production

logging:
  # OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

authentication:
  servers:
    - name: chat-service
      password:

redis:
  url:

gcm:
  senderId:
  apiKey:
  redphoneApiKey:

apn:
  pushCertificate:
  pushKey:
  voipCertificate:
  voipKey:

server:
  applicationConnectors:
    - type: http
      port:
