stage: staging

authentication:
  servers:
    - name: chat-service
      password:

redis:
  url:

gcm:
  senderId:
  apiKey:
  redphoneApiKey:

apn:
  pushCertificate:
  pushKey:
  voipCertificate:
  voipKey:

server:
  applicationConnectors:
    - type: http
      port:
